name = "proud-fog-47af"
main = "worker.js"
compatibility_date = "2023-10-25"

[vars]
u = "d3b84180-21db-49eb-832f-a39da5b34bc5"

[[kv_namespaces]]
binding = "C"
id = "7bd18c9e2da3424fbe8ef809eb949b37"
